### ISSUE TITLE
Client certs/keys

### ISSUE THREAD

**Issue by corporateanon** [kbrebanov/ansible-openvpn#1]
Where can i find the contents of the following parameters?
- openvpn_ca_certificate
- openvpn_client_certificate
- openvpn_client_key

Are they generated on the server side? Please, help me to point out the corresponding files.

**Comment by kbrebanov** [comment]
These variables are used when setting up a TLS client. You should already have generated the CA certificate, client certificate & key previously on a TLS server. You don't use files, you copy the 'content' of those specific files in the variables.

The last example in the README shows how to use these variables.

**Comment by corporateanon** [comment]
Oh, i see. Sorry for newbie questions, i am a certified novice at OpenVPN.

I was trying to make a server on one node and a client on another.
My client keys were not generated until i added the following variable:

```
    easy_rsa_clients:
      - client1
```

Then it worked. It was not in README, is it a correct use case?

**Comment by kbrebanov** [comment]
No problem. That is the correct use case.

In the README for the kbrebanov.openvpn role, it states that there is a dependency on the role kbrebanov.easy_rsa when using TLS certificates. The README of that role has an example on how to create a client certificate.

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
